[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[phases.chromium]
dependsOn = ["install"]
cmds = ["playwright install --with-deps chromium"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
