services:
  - type: web
    name: chaos-pipe
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python app.py
    plan: free
    envVars:
      - key: CIVITAI_API_KEY
        sync: true
